name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup emsdk
        uses: emscripten-core/setup-emsdk@v14

      - name: Build application
        run: |
          emcmake cmake -S . -B build
          make -C build

      - name: Package application
        run: |
          mkdir dist
          mv build/openloco.html dist/index.html
          mv build/openloco.js build/openloco.wasm  dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
